### ISSUE TITLE
Can't select spi dev bus parameter

### ISSUE THREAD

**Issue by schphil** [rpi-ws281x/rpi-ws281x-rust#10]
In the project I'm working on an Orange Pi Zero is used. From my understanding the spi dev bus parameter 0 cannot be used with the Orange PI Zero. Hence, it would nice to have the opportunity to set the value of the [spi dev bus parameter](https://github.com/jgarff/rpi_ws281x/blob/master/ws2811.c#L745) manually. In my case I would like to set it to 1. Is it possible to implement this feature? Or are there any reasons why you wouldn't do this? Thank you. :)

**Comment by JMurph2015** [comment]
Hi!
I can investigate this sometime in the next week or so.  The big question
is whether the underlying C API supports the functionality you're after.  I
think on most boards, the SPI devices are tied to pins, so setting the pin
selects the SPI device implicitly if I remember correctly.  I'll take a
harder look later and get back to you.
Thanks!

**Comment by JMurph2015** [comment]
I may or may not have forgotten to take that harder look, going to close for now, but if it is still bothering you feel free to reopen, present circumstances have driven me back to programming LED's in my spare time.
