### ISSUE TITLE
library demands /dev/mem access

### ISSUE THREAD

**Issue by anzbert** [rpi-ws281x/rpi-ws281x-rust#19]
I can only use this library as a root user , otherwise i get this error:

Can't open /dev/mem: Permission denied
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Mmap', examples/rpi-ws281x.rs:23:10

It works fine with sudo su.

my user is pi and is a member of the following groups:

pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi

is there a way of not needing root access to run this library ? gpiomem access should surely be enough

thanks!

**Comment by anzbert** [comment]
i think i worked it out. its the use of PWM that requires root.
[this thread](https://github.com/jgarff/rpi_ws281x/issues/396) 

can i use this library with spi?

**Comment by anzbert** [comment]
ah it worked now !! thx so much. ive copied the config values from your rusty controller

would it be ok to submit a pull request for a simple usage example?

**Comment by anzbert** [comment]
ah and another thing. could you possibly link to a newer version of bindgen? when using multiple C wrapped libraries, like yours and for example ableton-link-rs, your library is incompatible with the build because it uses a very old version of clang-sys, though its bindgen dependency. i solved it by forking and putting the latest bindgen in the cargo.toml.

but anyway. thx for the great work, i am so happy to have a working led controllor for my pi rust projects now :)

**Comment by JMurph2015** [comment]
I don't have easy access to a GitHub authenticated computer until Monday at
the earliest, but do know I saw your pull request and will take a look when
I get a chance.

**Comment by anzbert** [comment]
Thx!
