### ISSUE TITLE
LEDs start acting up if app run through systemd

### ISSUE THREAD

**Issue by BenBergman** [rpi-ws281x/rpi-ws281x-rust#31]
This probably isn't an issue with this library, but I'm not sure where else to get help figuring this out.

I've built an app with this library that drives about 150 LEDs (among other things). It works great when I run it manually and when I start the service after the Pi has fully booted. Running with a systemd service, it starts up fine and the LEDs look as expected, but about a second after the user logs in (auto-login enabled), the LEDs start acting - only the first ~5 LEDs are changing colour and it is not the pattern I've programmed. If I restart the service, the LEDs act normal. The rest of my app is still running fine, it is just the LED stuff that is being weird.

I'm currently running Raspbian 10 (Buster) on a Pi 4. I can probably test with the latest Raspberry Pi OS later.

**Comment by JMurph2015** [comment]
I haven't encountered that issue myself, but perhaps do you have a conflicting driver acting up?  Something like audio or SPI?

**Comment by JMurph2015** [comment]
Ah interesting, I couldn't say for sure, but glad it resolved for you.
